Write the connection and loading code

In [8]:
import os
from dotenv import load_dotenv

load_dotenv()

db_user = os.getenv("DB_USER")
db_password = os.getenv("DB_PASSWORD")
db_host = os.getenv("DB_HOST")
db_port = os.getenv("DB_PORT")
db_name = os.getenv("DB_NAME")

engine = create_engine(f"mysql+pymysql://{db_user}:{db_password}@{db_host}:{db_port}/{db_name}")

In [2]:
df = pd.read_csv("../data/cleaned_sales.csv")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,530331,22961,JUMBO BAG RED RETROSPOT,37,2025-08-28 17:08:00,2.08,17013.0,United Kingdom
1,530359,22457,CREAM CUPID HEARTS COAT HANGER,51,2025-10-13 11:48:00,2.75,13181.0,United Kingdom
2,530400,21212,PACK OF 72 RETROSPOT CAKE CASES,11,2025-12-18 16:59:00,0.55,17763.0,United Kingdom
3,530024,22720,POPCORN HOLDER,33,2025-09-17 03:55:00,0.85,17122.0,United Kingdom
4,530173,22961B,RABBIT NIGHT LIGHT,25,2025-07-30 01:20:00,2.08,18100.0,United Kingdom

In [6]:
df_to_load = df.rename(columns={
    "InvoiceNo": "invoice_no",
    "StockCode": "stock_code",
    "Description": "description",
    "Quantity": "quantity",
    "InvoiceDate": "invoice_date",
    "UnitPrice": "unit_price",
    "CustomerID": "customer_id",
    "Country": "country",
    "Revenue": "revenue"
})[["invoice_no", "stock_code", "description", "quantity", "invoice_date", "unit_price", "customer_id", "country", "revenue"]]

df_to_load.head()

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,revenue
0,530331,22961,JUMBO BAG RED RETROSPOT,37,2025-08-28 17:08:00,2.08,17013.0,United Kingdom,76.96
1,530359,22457,CREAM CUPID HEARTS COAT HANGER,51,2025-10-13 11:48:00,2.75,13181.0,United Kingdom,140.25
2,530400,21212,PACK OF 72 RETROSPOT CAKE CASES,11,2025-12-18 16:59:00,0.55,17763.0,United Kingdom,6.05
3,530024,22720,POPCORN HOLDER,33,2025-09-17 03:55:00,0.85,17122.0,United Kingdom,28.05
4,530173,22961B,RABBIT NIGHT LIGHT,25,2025-07-30 01:20:00,2.08,18100.0,United Kingdom,52.00

In [9]:
df_to_load = df.rename(columns={
    "InvoiceNo": "invoice_no",
    "StockCode": "stock_code",
    "Description": "description",
    "Quantity": "quantity",
    "InvoiceDate": "invoice_date",
    "UnitPrice": "unit_price",
    "CustomerID": "customer_id",
    "Country": "country",
    "Revenue": "revenue"
})[["invoice_no", "stock_code", "description", "quantity", "invoice_date", "unit_price", "customer_id", "country", "revenue"]]

df_to_load.head()

,invoice_no,stock_code,description,quantity,invoice_date,unit_price,customer_id,country,revenue
0,530331,22961,JUMBO BAG RED RETROSPOT,37,2025-08-28 17:08:00,2.08,17013.0,United Kingdom,76.96
1,530359,22457,CREAM CUPID HEARTS COAT HANGER,51,2025-10-13 11:48:00,2.75,13181.0,United Kingdom,140.25
2,530400,21212,PACK OF 72 RETROSPOT CAKE CASES,11,2025-12-18 16:59:00,0.55,17763.0,United Kingdom,6.05
3,530024,22720,POPCORN HOLDER,33,2025-09-17 03:55:00,0.85,17122.0,United Kingdom,28.05
4,530173,22961B,RABBIT NIGHT LIGHT,25,2025-07-30 01:20:00,2.08,18100.0,United Kingdom,52.00

In [10]:
df_to_load.to_sql("sales", con=engine, if_exists="append", index=False)

493